### ISSUE TITLE
Detectar el "macrigatismo"

### ISSUE THREAD

**Issue by mgaitan** [eypacha/macri-gato#2]
porque Macri gato es gato, sin lugar a dudas, pero tiene un séquito alrededor conocido como el **macrigatismo**, tanto simpatizantes y funcionarios, todos **macrigatistas** gatos.

![image](https://cloud.githubusercontent.com/assets/2355719/19973883/4e650836-a1c5-11e6-9eb6-de8544ee992f.png)

deberia decir "fundaciones vinculadas al macrigatismo"

![image](https://cloud.githubusercontent.com/assets/2355719/19973805/115a6bac-a1c5-11e6-9134-02f7ac443bd9.png)

y diputada "macrigatista".

**Comment by eypacha** [comment]
Gracias! no lo había pensado... ahora a pensar los regex correspondientes...

**Comment by eypacha** [comment]
Listo! y gracias...
