### ISSUE TITLE
La parte "gato" del icono casi no se ve

### ISSUE THREAD

**Issue by EmmanuelMess** [eypacha/macri-gato#4]
Propongo hacer el fondo dentro de la M de otro color (más oscuro) y el gato más curvo.

**Comment by eypacha** [comment]
Hola! Hablás del ícono en 16x16 o del logo en general? Aceptamos que nos mandes tu propuesta de manera gráfica...

**Comment by EmmanuelMess** [comment]
En general, no se me ocurre una solución.
